// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Modal() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div x-data=\"{ modal: false }\"><div class=\"modal\" id=\"modal-form\" class=\"modal-wrapper\" :class=\"{ &#39;is-active&#39;: modal }\" x-on:modal-ex.window=\"modal = !modal\"><div class=\"modal-background\" @click=\"modal = false\"></div><div class=\"modal-card\" id=\"modal-card\"><header class=\"modal-card-head\"><p class=\"modal-card-title\">Modal title</p><button type=\"button\" class=\"delete\" aria-label=\"close\" @click=\"modal = false\"></button></header><section class=\"modal-card-body\"><!-- Content ... --></section><footer class=\"modal-card-foot\"><button type=\"button\" class=\"button is-success\">Save changes</button> <button type=\"button\" class=\"button\" @click=\"modal = false\">Cancel</button></footer></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
